name: 2019nCoV CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
    - uses: actions/checkout@master
    - name: Run Tests
      uses: skx/github-action-tester@master
      with:
        script: yarn test
  
  deploy-to-digital-ocean-droplet:
    runs-on: ubuntu-latest
    name: Deploy 2019nCoV visualizer
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Pull from GitHub
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.KEY }}
          script: cd covid-19-info/ && git pull && yarn build
